### ISSUE TITLE
Geste zum Klick eines UI Buttons

### ISSUE THREAD

**Issue by BlayTheNinth** [AntoniaBe/Interactive_platformer#28]

**Comment by BlayTheNinth** [comment]
Siehe feature/click_gesture, muss noch mit Leap Motion getestet werden.

Testszene: ClickGestureTest
1. Fährt man mit dem Zeigefinger über den Button, sollte er sich rot färben
2. Bei Klickbewegung (Zeigefinger muss über Button liegen und sich in Richtung Bildschirm bewegen) sollte der Text des Buttons sich in "CLICKED" ändern

**Comment by AntoniaBe** [comment]
Habe gerade die Testszene getestet und bekomme folgende Fehlermeldung:

![fehlermeldung](https://user-images.githubusercontent.com/15321778/34527850-3c19f57e-f0a7-11e7-9c7a-e0496b9beafb.JPG)

und die Hand bzw die Finger sind hinter dem Button:

![handhinterbutton](https://user-images.githubusercontent.com/15321778/34527861-48c824c6-f0a7-11e7-91d2-1b349f43526b.JPG)

**Comment by BlayTheNinth** [comment]
REPARIEREN.

**Comment by BlayTheNinth** [comment]
Sollte jetzt funktionieren. Habe es nochmal mit nem Dummy-Objekt als Hand versucht, und damit läuft es.

Voraussetzung ist jetzt, dass entweder Mittelfinger oder Zeigefinger ausgestreckt sind (andere Finger egal). Falls die Szene sich wieder nicht öffnen lässt, habe ich auch ein Prefab für den Testcanvas reingelegt (nicht vergessen, die Render Camera im Inspektor zu setzen). 

Button soll beim Rüberfahren mit dem Finger rot werden, und wenn der Finger mit mehr als `Min Velocity` (momentan 0.1) in Richtung des Bildschirms bewegt wird, wird es als Klick gewertet. `Min Velocity` muss ggf. noch angepasst werden.
